ros-controls/ros2_control_demos

.github/workflows/linters.yaml, ros2_control_demo_communication_gazebo/CMakeLists.txt, ros2_control_demo_communication_gazebo/package.xml, ros2_control_demo_communication_headless/CMakeLists.txt, ros2_control_demo_communication_headless/package.xml, ros2_control_demo_hardware/CMakeLists.txt, ros2_control_demo_hardware/package.xml, ros2_control_demo_robot/CMakeLists.txt, ros2_control_demo_robot/package.xml
cmake clean  as discussed in #4, #16 and #17
=> Clean cmake

.github/workflows/linters.yaml
Hello, this is a PR according to the issue #54.
=> Update linter workflow.

README.md, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp, ros2_control_demo_hardware/src/rrbot_system_position_only.cpp, ros2_control_demo_robot/CMakeLists.txt, ros2_control_demo_robot/config/rrbot_controllers.yaml, ros2_control_demo_robot/description/rrbot/rrbot.materials.xacro, ros2_control_demo_robot/description/rrbot/rrbot.urdf.xacro, ros2_control_demo_robot/description/rrbot/rrbot_system_position_only.ros2_control.xacro, ros2_control_demo_robot/description/rrbot_system_position_only.urdf.xacro, ros2_control_demo_robot/launch/rrbot_system_position_only.launch.py, ros2_control_demo_robot/launch/test_rrbot_description.launch.py, ros2_control_demo_robot/package.xml, ros2_control_demo_robot/rviz/rrbot.rviz
Replaces a part of the #53 and resolves #69 
fixes mostly trivial changes and make the example more "exemplary" :)
=> Add corrections and extensions for the rrbot

ros2_control_demo_robot/config/diffbot_diff_drive_controller.yaml, ros2_control_demo_robot/launch/diffbot_system.launch.py
fixes https://github.com/ros-controls/ros2_control_demos/issues/93
=> correct diffdrive demo

README.md, doc/index.rst, ros2_control_demo_bringup/CMakeLists.txt, ros2_control_demo_bringup/launch/rrbot.launch.py, ros2_control_demo_bringup/launch/rrbot_system_position_only_gazebo.launch.py, ros2_control_demo_description/rviz/diffbot.rviz, ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp, ros2_control_demo_hardware/src/diffbot_system.cpp
Fix for @jordan-palacios review of PR #76 
* Fix README.md numbering
* Add diffrobot.rviz
* Implements a differentiable wheel robot kinematics. (i did not understood the previous implementation) So probably this is the part that should be fixed first.
* Fix rrbot.launch.py problem with --load-only
TODO: further checks probably to be done
=> Add rrbot corrections following review of @jordan-palacios

ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp, ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp
I was a little confused about what this vector did when reading the code. Is it some kind of vector of possible control modes for each actuator? Or a vector of current control modes for all actuators? Added a comment to clarify.
I also did some minor renaming:  `lvl` --> `level` for readability and consistency.
=> Rename and document control_level vector

README.md
First part of replacing #118.﻿
=> Update README introduction to be more precise and correct

.github/reviewer-lottery.yml, .github/workflows/reviewer_lottery.yml
Copied from ros2_control repo.
=> Add reviewer Lottery to repository.

doc/index.rst
Add missing space in demos doc
=> Fix a typo

ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/external_rrbot_force_torque_sensor.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_actuator.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_with_sensor.hpp, ros2_control_demo_hardware/src/diffbot_system.cpp, ros2_control_demo_hardware/src/external_rrbot_force_torque_sensor.cpp, ros2_control_demo_hardware/src/rrbot_actuator.cpp, ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp, ros2_control_demo_hardware/src/rrbot_system_position_only.cpp, ros2_control_demo_hardware/src/rrbot_system_with_sensor.cpp
This PR adds some small optimizations and fixes for examples.
=> Small fixes and optimizations of examples.

README.md, ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/external_rrbot_force_torque_sensor.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_actuator.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp, ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_with_sensor.hpp, ros2_control_demo_hardware/src/diffbot_system.cpp, ros2_control_demo_hardware/src/external_rrbot_force_torque_sensor.cpp, ros2_control_demo_hardware/src/rrbot_actuator.cpp, ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp, ros2_control_demo_hardware/src/rrbot_system_position_only.cpp, ros2_control_demo_hardware/src/rrbot_system_with_sensor.cpp
Counterpart of https://github.com/ros-controls/ros2_control/pull/715
=> Pass time and period to read() and write()

README.md
I'm hoping this will catch the eye of first-time users and point them towards the minimal example.
=> Add First-Time Users section to the README

ros2_control_demo_hardware/CMakeLists.txt
=> Fix DLL export defintion.

ros2_control_demo_hardware/src/rrbot_system_with_sensor.cpp
=> Fix bug that doesn't reset commands properly on activation.

README.md
=> Publish to correct topic in DiffBot example

.github/workflows/rolling-rhel-binary-build.yml
- point rhel ci job to ghcr.io/ros-controls/ros:rolling-rhel
=> ci: :construction_worker: update rhel container

example_1/doc/userdoc.rst, example_2/doc/userdoc.rst, example_3/doc/userdoc.rst, example_4/doc/userdoc.rst, example_5/doc/userdoc.rst, example_6/doc/userdoc.rst, example_8/doc/userdoc.rst
=> Docs: fix paths

example_1/README.md, example_2/README.md, example_3/README.md, example_4/README.md, example_5/README.md, example_6/README.md, example_8/README.md
As suggested in #261 I added a brief readme in every example folder.
=> Add readmes in every example folder

.github/reviewer-lottery.yml
Please consider the guidelines from [CONTRIBUTING.md](CONTRIBUTING.md) before you open a pull request.
=> Update reviewer lottery

example_1/bringup/config/rrbot_joint_trajectory_publisher.yaml
Fixes deprecation warnings introduced with https://github.com/ros-controls/ros2_controllers/pull/389
=> JTC: Use new goal definition structure

ros2_control_demos-not-released.rolling.repos, ros2_control_demos.humble.repos, ros2_control_demos.rolling.repos
While preparing #307 I forgot to cleanup the repos files to update the Gazebo repositories.
=> Cleanup repos files

ros2_control_demo_description/diffbot/urdf/diffbot_description.urdf.xacro
New PR that points to `master` branch, replacing #372
=> [DiffBot] Inertia fix

.github/dependabot.yml
=> [CI] Dependabot config for humble

.github/workflows/reviewer_lottery.yml
Manual backport of #397 #401 #403
=> [CI] Don't run reviewer lottery from bots (backport #397 #401 #403)

.github/workflows/rolling-pre-commit.yml
Necessary changes to make https://github.com/ros-controls/ros2_control_ci/pull/53 work for noble.
=> [CI] Specify runner/container images

example_15/bringup/config/rrbot_namespace_forward_position_publisher.yaml, example_15/bringup/launch/rrbot_namespace.launch.py, example_2/bringup/launch/diffbot.launch.py, example_2/doc/userdoc.rst, example_7/bringup/launch/r6bot_controller.launch.py
This fixes some wrong/outdated topic remappings
=> Fix topic remappings

.github/workflows/humble-semi-binary-build.yml, .github/workflows/iron-semi-binary-build.yml, .github/workflows/rolling-semi-binary-build.yml
Similar to https://github.com/ros-controls/ros2_control/pull/1876
=> Don't test main on semi-binary

example_13/bringup/launch/three_robots.launch.py
Already included in #667 with the necessary remapping on humble.
=> Remove unused robot_description parameter

ros2_control_demos.humble.repos, ros2_control_demos.jazzy.repos, ros2_control_demos.rolling.repos
Add the repo to the semi-binary builds
=> Add control_toolbox repo

.github/workflows/humble-binary-build.yml, .github/workflows/humble-semi-binary-build.yml, .github/workflows/rolling-binary-build.yml, .github/workflows/rolling-semi-binary-build.yml
=> Also run CI workflows if pluginlib xml is changed

example_11/CMakeLists.txt, example_11/test/test_carlikebot_launch.py, example_11/test/test_carlikebot_launch_remapped.py
=> Add topic remap test (backport #577, #695, #700)

ros2_control_demos.jazzy.repos
https://github.com/ros-controls/realtime_tools/pull/263
=> Use jazzy branch for realtime_tools

example_13/test/test_three_robots_launch.py
=> Increase sigterm timeout

example_7/controller/include/ros2_control_demo_example_7/r6bot_controller.hpp, example_7/controller/r6bot_controller.cpp, example_7/doc/userdoc.rst
- Removed unnecessary or empty callback functions from the controller code.
- Revised the associated documentation to reflect these changes.
=> Removed empty callbacks in controllers and updated documentation (#685)

Dockerfile/Dockerfile, doc/index.rst
Use correct launch file argument in docker entry point and some more details in the installation description
=> Update to docker file and install description

example_9/CMakeLists.txt, example_9/bringup/launch/rrbot_gazebo.launch.py, example_9/doc/userdoc.rst, example_9/test/test_rrbot_gazebo_launch.py
As we saw with #755, there was no test of the gazebo launch file.
=> Activate integration test of gazebo example 9

stale.yml
Tested with https://github.com/ros-controls/ros2_controllers/pull/1605, rolling out to all repos.
=> Add workflow for actions/stale

example_10/hardware/rrbot.cpp, example_4/hardware/rrbot_system_with_sensor.cpp
Two more occurrences similar to https://github.com/ros-controls/ros2_control_demos/pull/774
Fixes https://github.com/ros-controls/ros2_control_ci/issues/301
Fixes https://github.com/ros-controls/ros2_control_ci/issues/302
Fixes #777
=> Cast to double instead of float

example_1/bringup/config/rrbot_joint_trajectory_publisher.yaml
Just  changed the yaml file structure since it was deprecated for humble version.
if it is wanted I can edit others as well before the merge.
=> Fix deprecated structure

ros2_control_demo_description/carlikebot/urdf/carlikebot_description.urdf.xacro
Steering is broken since the joint_limiter is active
=> Fix velocity limit of carlike bot

.gitignore
Similar to https://github.com/ros-controls/control_toolbox/pull/341
=> Remove gitignore

example_1/test/test_rrbot_launch.py, example_1/test/test_rrbot_launch_cli_direct.py, example_10/test/test_rrbot_launch.py, example_11/test/test_carlikebot_launch.py, example_11/test/test_carlikebot_launch_remapped.py, example_12/test/test_rrbot_launch.py, example_13/test/test_three_robots_launch.py, example_14/test/test_rrbot_modular_actuators_without_feedback_sensors_for_position_feedback_launch.py, example_15/test/test_multi_controller_manager_launch.py, example_15/test/test_rrbot_namespace_launch.py, example_16/test/test_diffbot_launch.py, example_2/test/test_diffbot_launch.py, example_3/test/test_rrbot_system_multi_interface_launch.py, example_4/test/test_rrbot_system_with_sensor_launch.py, example_5/test/test_rrbot_system_with_external_sensor_launch.py, example_6/test/test_rrbot_modular_actuators_launch.py, example_7/test/test_r6bot_controller_launch.py, example_8/test/test_rrbot_transmissions_system_position_only_launch.py, example_9/test/test_rrbot_gazebo_launch.py, example_9/test/test_rrbot_launch.py
No I'm not working with cranes 😇
=> Fix copy pasta

example_1/CMakeLists.txt, example_10/CMakeLists.txt, example_11/CMakeLists.txt, example_12/CMakeLists.txt, example_12/package.xml, example_14/CMakeLists.txt, example_16/CMakeLists.txt, example_2/CMakeLists.txt, example_3/CMakeLists.txt, example_4/CMakeLists.txt, example_5/CMakeLists.txt, example_6/CMakeLists.txt, example_7/CMakeLists.txt, example_7/package.xml, example_8/CMakeLists.txt, example_9/CMakeLists.txt, ros2_control_demos/package.xml
and some minor updates to dependencies
=> Use target_link_libraries instead of ament_target_dependencies

.github/workflows/humble-pre-commit.yml, .github/workflows/rolling-pre-commit.yml
See https://github.com/ros-controls/ros2_control_ci/issues/384 for reference
=> Run workflow on pushes to save cache

.github/workflows/humble-check-docs.yml, .github/workflows/rolling-check-docs.yml
https://github.com/ros-controls/control_toolbox/pull/424
=> Improve paths filtering of docs CI job

example_13/doc/userdoc.rst, example_13/test/test_three_robots_launch.py
=> Don't activate controller with command_interfaces if hw is inactive

example_7/controller/r6bot_controller.cpp, example_7/doc/userdoc.rst
https://github.com/ros-controls/ros2_controllers/pull/1910
=> Remove release_interfaces call
