README.md

- Remove a warning about unstable API since (as far as I know) the API should be stable now.
- Add a hints section for those coming from ros(1)_control.
- Reduce wordiness in a few places. It seemed like there was some redundancy, especially in stating goals of the package multiple times.
- Minor grammar cleanup.

Reduce wordiness, add hints for those coming from ros(1)_control

---

ros2_control_demo_hardware/CMakeLists.txt
ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp
ros2_control_demo_hardware/ros2_control_demo_hardware.xml
ros2_control_demo_hardware/src/diffbot_system.cpp
ros2_control_demo_hardware/src/rrbot_system_position_only.cpp
ros2_control_demo_robot/controllers/diffbot_diff_drive_controller.yaml
ros2_control_demo_robot/description/diffbot/diffbot.gazebo.xacro
ros2_control_demo_robot/description/diffbot/diffbot.materials.xacro
ros2_control_demo_robot/description/diffbot/diffbot.urdf.xacro
ros2_control_demo_robot/description/diffbot/diffbot_system.ros2_control.xacro
ros2_control_demo_robot/description/diffbot_system.urdf.xacro
ros2_control_demo_robot/launch/diffbot_system.launch.py

Resolves #50 
- A diffbot folder was created similar to rrbot for URDF files;
- A hardware in ros2_control_demo_hardware was created with position and velocity states and velocity command;
- Launch file was added into ros2_control_demo_robot.

demo_diff_drive_controller

---

.github/workflows/ci-build-coverage.yml

Codecov recently announced an issue with their bash upload script.
Details of the incident can be found at https://about.codecov.io/security-update/
In order to help protect against similar future issues, the
codecov-action was first updated in 1.4.0 to verify the script after
downloading and in 1.5.0 the current version of the upload script has
been vendored into the action.
Workflows which specify the `@v1` tag will automatically use the latest
1.x version of the action as long as codecov continue to update the v1
tag. Since this workflow uses pinned action versions I have updated the
version to 1.5.0. Any version >=1.4.0 is sufficient to verify the upload
script but since 1.5.0 is the latest version as of now I decided to bump
to it.

Upgrade codecov-action version.

---

.github/workflows/ci-build-coverage.yml
.github/workflows/ci-build-source.yml
.github/workflows/ci-ros-lint.yaml
README.md
ros2_control_demo_bringup/launch/rrbot_system_position_only.launch.py
ros2_control_demo_description/launch/view_robot.launch.py
ros2_control_demo_description/urdf/rrbot_system_multi_interface.urdf.xacro

* Correct URDF macro
* Add multiple interface commands in the README.md
* Fix controller name for forward_command_controller_position

 Make multiple_interfaces works on branch add-rrbot-corrections.

---

ros2_control_demo_bringup/package.xml
ros2_control_demo_description/package.xml

This matters to us because we install per-package, not per git repository.

The dependency is one down

---

README.md

The file was moved in this PR: https://github.com/ros-controls/ros2_control_demos/pull/113/files#diff-116a24065c375742d785438bd04d24b64cb4b9222922e036e605e40fefa17c7a
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

Fix path to rrbot.rviz in README

---

README.md
ros2_control_demo_bringup/config/rrbot_controllers.yaml
ros2_control_demo_bringup/config/rrbot_joint_trajectory_publisher.yaml
ros2_control_demo_bringup/launch/test_joint_trajectory_controller.launch.py
ros2_control_test_nodes/ros2_control_test_nodes/publisher_joint_trajectory_controller.py
ros2_control_test_nodes/setup.py

Replaces #90.﻿
This is moved from `add_demo_nodes` branch and tested with multiple different robots and simulations.

Add JTC publisher into demo node and show its usage in readme

---

ros2_control_demo_bringup/config/rrbot_joint_trajectory_publisher.yaml
ros2_control_test_nodes/ros2_control_test_nodes/publisher_joint_trajectory_controller.py

The PR aims to prepare joint_trajectory_publisher for checking the start conditions.
PR info:
- This is very useful when launching test nodes on the real hardware to protect the robot from collision.
- The start state check can be disabled by the configuration file
- Tackling [UR#94](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/94)
Example of config file:
```
publisher_joint_trajectory_controller:
ros__parameters:
controller_name: "joint_trajectory_controller"
wait_sec_between_publish: 6
goal_names: ["pos1", "pos2", "pos3", "pos4"]
pos1: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
pos2: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
pos3: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
pos4: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
joints:
- shoulder_pan_joint
- shoulder_lift_joint
- elbow_joint
- …
```

Add check of start state for trajectory publisher

---

.github/workflows/ci-build-semi-binary.yml
ros2_control_demo_hardware/CMakeLists.txt
ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp
ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp
ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp
ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_with_sensor.hpp
ros2_control_demo_hardware/package.xml
ros2_control_demo_hardware/src/diffbot_system.cpp
ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp
ros2_control_demo_hardware/src/rrbot_system_position_only.cpp
ros2_control_demo_hardware/src/rrbot_system_with_sensor.cpp

- Migrating from Foxy to Galactic
- Add missing updates from #133
Replaces #137 
@liushuya7 sorry I did mistake by force-pushing to your branch and now opened this PR.

Migrating from Foxy to Galactic

---

README.md
ros2_control_demo_bringup/config/diffbot_controllers.yaml
ros2_control_demo_bringup/config/rrbot_controllers.yaml
ros2_control_demo_bringup/config/rrbot_multi_interface_forward_controllers.yaml
ros2_control_demo_bringup/launch/diffbot.launch.py
ros2_control_demo_bringup/launch/rrbot.launch.py
ros2_control_demo_bringup/launch/rrbot_base.launch.py
ros2_control_demo_bringup/launch/rrbot_system_multi_interface.launch.py
ros2_control_demo_bringup/launch/rrbot_system_position_only.launch.py
ros2_control_demo_bringup/launch/rrbot_system_position_only_gazebo.launch.py
ros2_control_demo_bringup/launch/rrbot_system_with_external_sensor.launch.py
ros2_control_demo_bringup/launch/rrbot_system_with_sensor.launch.py
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_multi_interface.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_position_only.ros2_control.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_multi_interface.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_position_only.urdf.xacro
ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp
ros2_control_demo_hardware/src/diffbot_system.cpp
ros2_control_demo_hardware/src/external_rrbot_force_torque_sensor.cpp
ros2_control_demo_hardware/src/rrbot_actuator.cpp
ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp
ros2_control_demo_hardware/src/rrbot_system_position_only.cpp
ros2_control_demo_hardware/src/rrbot_system_with_sensor.cpp

sits on top #124
fourth part of #118 
Main changes:
- correct structure and header of "position only" example using rrbot_base.launch.py
- add links into README
- optimized behavior of multi interface example
- added start delay for rviz and controller spawner after JSB has been started. (This reduces warnings in output).
- added comments in the code what is exemplary-code to not be copied into production
- corrected nomenclarute: "start" --> "activate"; "stop" --> "deactivate"

Improve docs and behavior on complex examples.

---

ros2_control_demo_bringup/config/diffbot_controllers.yaml

* `publish_cmd` seems to be replaced with `publish_limited_velocity`
* `publish_wheel_data` seems to be not ported from ros1
* `preserve_turning_radius` seems to have never merged into ros1 and doesn't exist in ros2 either
Just ran into this as I was using it as reference for what parameters are available to play with. Is there some source of documentation to look for these things(like http://wiki.ros.org/diff_drive_controller#Parameters in ros1)?

remove invalid diff_drive_controller parameters

---

ros2_control_demo_description/rrbot_description/ros2_control/external_rrbot_force_torque_sensor.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_modular_actuators.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_multi_interface.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_position_only.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_with_sensor.ros2_control.xacro

This PR fixes a bug where prefixes of joint names are ignored in URDF which causes problem when using prefix, e.g., when running multiple instances of hardware.﻿
P.S. CI is failing because it has to be updated after transition to jammy. So, I would like to proceed with this anyway.

Bugfix: Do not ignore prefix argument for joint names.

---

ros2_control_demo_bringup/launch/diffbot.launch.py
ros2_control_demo_bringup/launch/rrbot.launch.py
ros2_control_demo_bringup/launch/rrbot_base.launch.py

Fix this warning due to a recent ROS2 Rolling update:
`[ERROR] [launch]: Caught exception in launch (see debug for traceback): stdoutstderr is not a valid standard output config i.e. "screen", "log" or "both"`

Fix warning about "output" from launch files

---

ros2_control_demo_bringup/launch/rrbot_base.launch.py
ros2_control_demo_bringup/launch/rrbot_system_position_only_gazebo.launch.py
ros2_control_demo_description/diffbot_description/urdf/diffbot_system.urdf.xacro
ros2_control_demo_description/rrbot_description/ros2_control/external_rrbot_force_torque_sensor.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_modular_actuators.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_multi_interface.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_position_only.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_with_sensor.ros2_control.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_modular_actuators.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_multi_interface.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_position_only.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_with_external_sensor.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_with_sensor.urdf.xacro

The `use_sim` arg was used to choose between Gazebo simulation or ros2_control `fake_components` simulation. Since they are both types of simulation, I propose renaming the arg to `use_gazebo`.

Replace use_sim with use_gazebo

---

README.md
ros2_control_demo_bringup/config/rrbot_controllers.yaml
ros2_control_demo_bringup/config/rrbot_joint_trajectory_publisher.yaml
ros2_control_demo_bringup/launch/rrbot.launch.py
ros2_control_demo_bringup/launch/rrbot_base.launch.py
ros2_control_demo_bringup/launch/test_joint_trajectory_position_controller.launch.py
ros2_control_test_nodes/ros2_control_test_nodes/publisher_joint_trajectory_controller.py
ros2_control_test_nodes/ros2_control_test_nodes/publisher_joint_trajectory_position_controller.py
ros2_control_test_nodes/setup.py

Hello,
I am learning the ros2 control framework and found that there was a discrepancy in the naming consistency for the joint_trajectory_controller. To add clarity, I have renamed the controller to joint_trajectory_controller which fits well with the publisher and actual controller implementation names.
Additionally, I changed the spawner argument from -c to --controller-manager because these arguments were used interchangeably and was confusing for the learning. I guess the --controller-manager is more for a new learner..
Best,
Haider

Rename position_trajectory_controller to joint_trajectory_controller

---

ros2_control_demo_bringup/launch/rrbot_base.launch.py
ros2_control_demo_bringup/launch/rrbot_system_multi_interface.launch.py
ros2_control_demo_bringup/launch/rrbot_system_position_only.launch.py
ros2_control_demo_bringup/launch/rrbot_system_with_external_sensor.launch.py
ros2_control_demo_bringup/launch/rrbot_system_with_sensor.launch.py
ros2_control_demo_description/diffbot_description/ros2_control/diffbot_system.ros2_control.xacro
ros2_control_demo_description/diffbot_description/urdf/diffbot_system.urdf.xacro
ros2_control_demo_description/rrbot_description/ros2_control/external_rrbot_force_torque_sensor.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_multi_interface.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_position_only.ros2_control.xacro
ros2_control_demo_description/rrbot_description/ros2_control/rrbot_system_with_sensor.ros2_control.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_multi_interface.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_position_only.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_with_external_sensor.urdf.xacro
ros2_control_demo_description/rrbot_description/urdf/rrbot_system_with_sensor.urdf.xacro

This PR resolves #193 issue to refactor all of `fake_sensor_commands` to `mock_sensor_commands`. The dependent issue https://github.com/ros-controls/ros2_control/issues/774 is resolved by the PR https://github.com/ros-controls/ros2_control/pull/782

fake_sensor_commands renamed

---

.github/workflows/ci-format.yml
.pre-commit-config.yaml
ros2_control_demo_hardware/src/rrbot_system_multi_interface.cpp
ros2_control_test_nodes/ros2_control_test_nodes/publisher_forward_position_controller.py

- Use pydocstyle instead of pep257 because it replaces it.
- Bump versions of hooks.
- Remove fixed python version from formatting action.
- Fix action warnings about Node.js 12 by updating them.
- Bump version of clang-format.
- correct formatting.

🔧 Fixes and updated on pre-commit hooks and their action.

---

example_8/hardware/rrbot_transmissions_system_position_only.cpp

Adjusted to ros2_control commit to split interfaces: https://github.com/ros-controls/ros2_control/pull/938/files

[Example 8] split hw interfaces -> state & command interfaces

---

example_1/doc/userdoc.rst
example_2/doc/userdoc.rst
example_3/doc/userdoc.rst
example_4/doc/userdoc.rst
example_5/doc/userdoc.rst
example_6/doc/userdoc.rst
example_8/doc/userdoc.rst

Info is coming from [the roadmap](https://github.com/ros-controls/roadmap/blob/master/design_drafts/components_architecture_and_urdf_examples.md) where applicable, as suggested in #262.

Add more information to example docs

---

.github/workflows/rolling-rhel-binary-build.yml

This workflow always failed -> I copied the configuration from https://github.com/ros-controls/ros2_control/pull/983
Do we need this here at all @bmagyar?

Remove RHEL builds from PRs

---

example_2/hardware/diffbot_system.cpp
example_2/hardware/include/ros2_control_demo_example_2/diffbot_system.hpp

The kinematics calculation was without any use in the hw interface. 
Maybe the original intention was to simulate some odometry sensors, or to perform the state integration in world coordinates?
I removed it now, and also split the command output from the state integration into the read/write method.

[example_2] Remove kinematics from diffbot

---

doc/index.rst
example_1/doc/userdoc.rst
example_2/doc/userdoc.rst
example_3/doc/userdoc.rst
example_4/doc/userdoc.rst
example_5/doc/userdoc.rst
example_6/doc/userdoc.rst
example_8/doc/userdoc.rst

A companion PR to https://github.com/ros-controls/control.ros.org/pull/82

Fix docs format

---

example_4/description/rviz/rrbot.rviz
example_4/description/urdf/rrbot_description.urdf.xacro
example_4/hardware/rrbot_system_with_sensor.cpp
example_5/description/urdf/rrbot_description.urdf.xacro

I deleted a bit too much with #246 -> re-added the missing links now.
I also fixed the slowdown calculation of example 4.

[Example4+5] Fix tool link and slowdown

---

example_1/doc/userdoc.rst
example_2/doc/userdoc.rst
example_3/doc/userdoc.rst
example_4/doc/userdoc.rst
example_5/doc/userdoc.rst
example_6/doc/userdoc.rst
example_8/doc/userdoc.rst

Using branch name substitutions now for every link. 
For details see https://github.com/ros-controls/control.ros.org/pull/98

Docs: Use branch name substitution for all links

---

.clang-format

Currently, as the ReflowComments are not enabled, the 100 columns limit is only applied to the code but not to the comments, and in the end, the CI checks are failing in this regard. By enabling the ReflowComments, this should be solved

enable ReflowComments to also use ColumnLimit on comments

---

example_1/package.xml
example_2/package.xml
example_3/package.xml
example_4/package.xml
example_5/package.xml
example_6/package.xml
example_8/package.xml

While trying to add dockerfiles for this repo it was throwing this:
```
ros2: error: argument Call `ros2 <command> -h` for more detailed usage.: invalid choice: 'launch'
```
Solution inspired by:
https://github.com/ros-controls/gz_ros2_control/blob/master/gz_ros2_control_demos/package.xml#L36
the other launch deps are not needed since they are already listed for ros2launch.

fix "ros2 invalid choice: 'launch'" by rosdep install

---

.github/workflows/ci-format.yml
example_1/package.xml
example_2/package.xml
example_3/package.xml
example_4/package.xml
example_5/package.xml
example_6/package.xml
example_8/package.xml

Apologies for missing this.
resolves this issue:
```
root@d33280b944cb:/home/ros2_ws# ros2 launch ros2_control_demo_example_2 diffbot.launch.py 
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-06-01-21-42-05-434293-d33280b944cb-83
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable '[<launch.substitutions.text_substitution.TextSubstitution object at 0x7ff5141948b0>]' not found on the PATH
```
once again inspired by:
https://github.com/ros-controls/gz_ros2_control/blob/master/gz_ros2_control_demos/package.xml#L47
Also I checked all the examples so they should all be fine to run in docker using rosdep after this.

Add xacro as exec depend

---

example_1/bringup/config/rrbot_controllers.yaml

`state_publish_rate` was removed by https://github.com/ros-controls/ros2_controllers/pull/520/files

Remove outdated state_publish_rate for JTC

---

doc/index.rst
example_1/doc/userdoc.rst
example_2/doc/userdoc.rst
example_3/doc/userdoc.rst
example_4/doc/userdoc.rst
example_5/doc/userdoc.rst
example_6/doc/userdoc.rst
example_8/doc/userdoc.rst

Another PR for updating the branch-dependent links. 
For details see https://github.com/ros-controls/control.ros.org/pull/98

Use {REPOS_FILE_BRANCH} also in github_url

---

example_1/bringup/launch/rrbot.launch.py
example_1/package.xml
example_2/bringup/launch/diffbot.launch.py
example_2/package.xml
example_3/bringup/launch/rrbot_base.launch.py
example_3/package.xml
example_4/bringup/launch/rrbot_base.launch.py
example_4/package.xml
example_5/bringup/launch/rrbot_base.launch.py
example_5/package.xml
example_6/bringup/launch/rrbot_base.launch.py
example_6/package.xml
example_8/bringup/launch/rrbot_base.launch.py
example_8/package.xml

getting rid of this warning:
https://github.com/ros-controls/ros2_control/blob/master/controller_manager/src/controller_manager.cpp#L160C1-L167
and joint_state_publisher_gui wasn't installed when running view_robot.launch.py inside docker.

add a dependency; fix deprecation warning

---

.github/workflows/humble-docker-build.yaml
.github/workflows/rolling-binary-build.yml
.github/workflows/rolling-docker-build.yaml
Dockerfile/Dockerfile

- Apply some good practice for docker files (cleanups)
- Fix `rosdep --skip-keys`
- Create workflows to regularly build the docker image
- Remove remnant of Gazebo - PR

Touchup Dockerfile and create a workflow building it

---

.github/ISSUE_TEMPLATE/good-first-issue.md

This fixes some links pointing to broken ros-controls.github.io URLs.

Fix links to control.ros.org

---

.github/workflows/ci-ros-lint.yml

ros-rolling-ament-cpplint seems not to be released for ubuntu 20.04 any more.

Fix ubuntu version for cpplint

---

.github/workflows/ci-ros-lint.yml

Follow-up to #330 Now, also copyright, cppcheck and lint_cmake fail.
`AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS` needs to be set to run it.

[CI] Bump ubuntu version of second ament_lint job

---

README.md
doc/index.rst

Improve docs by adding explicit info about the ROS 2 distro, close #344.
rst for rolling will be rendered this way:

Add info about ROS 2 distro

---

example_2/hardware/diffbot_system.cpp

The hardware interface for diffbot (example 2) integrates motor position data using the 2nd motor's position for both motors. This causes odometry to report movement along a single axis only. This PR fixes the issue and restores expected odometry behaviour.

Fix diffbot position integration

---

example_1/doc/userdoc.rst
example_12/README.md

This PR is fixing simple stuff on top of the amazing recent work on documenting this repo. 
In example 1, the first step is optional and RViz should be closed, and the second step start also RViz. Plus there is two in as some point.
In example 12, the file README.md is giving the wrong title for the example.

Minor fixes in documentation (example_1 and example_12)

---

Dockerfile/entrypoint.sh
doc/run_from_docker.rst
example_1/doc/userdoc.rst

Using the sphinx tabs plugin, we could improve the instructions using the docker container.
Choosing one tab switches all group-tabs at once (as known from docs.ros.org). What do you think? Did that only for example 1, but would apply the changes to the others, too.

Update docker instructions

---

example_14/hardware/rrbot_sensor_for_position_feedback.cpp

As commented with #334, there was an missing return type of the lambda function.

[Example 14] Fix return type of lambda

---

example_2/bringup/launch/diffbot.launch.py
example_2/description/ros2_control/diffbot.ros2_control.xacro
example_2/description/urdf/diffbot.urdf.xacro
example_2/doc/userdoc.rst
example_3/bringup/launch/rrbot_system_multi_interface.launch.py
example_3/description/ros2_control/rrbot_system_multi_interface.ros2_control.xacro
example_4/bringup/launch/rrbot_system_with_sensor.launch.py
example_4/description/ros2_control/rrbot_system_with_sensor.ros2_control.xacro
example_5/bringup/launch/rrbot_system_with_external_sensor.launch.py
example_5/description/ros2_control/external_rrbot_force_torque_sensor.ros2_control.xacro
example_5/description/ros2_control/rrbot_system_position_only.ros2_control.xacro
example_6/bringup/launch/rrbot_modular_actuators.launch.py

I implemented the mock_hardware for the diffbot to test https://github.com/ros-controls/ros2_control/pull/1028
It simply works ;)
This PR closes #254.

Adding mock_hardware to diffbot and update docs for all usages

---

example_7/doc/userdoc.rst

Fixed a few typo in Example 7 documentation.

fix typo in example7 doc

---

README.md

Rename Getting Started to Structure and added a new Getting Started section that links to the installation documentation.

Suggestion for improvement of the README.md 

---

.github/reviewer-lottery.yml

I created a [python script](https://gist.github.com/christophfroehlich/007964f5e6cf2a99a919212d48b3dc5c) parsing closed reviews of a repository and making some statistics: 
[reviewers_ros-controls_ros2_control_demos_2023-12-04.csv](https://github.com/ros-controls/ros2_control_demos/files/13590680/reviewers_ros-controls_ros2_control_demos_2023-12-04.csv)
Thanks for the work of lots of active reviewers! 
But to make that process more efficient, I removed all reviewers from the list which 
a) never finished any review
b) haven't reviewed anything in 2023
Additionally, I promote the following reviewers having already more than approx. 10 reviews and being still active :)
@fmauch
@moriarty 
@olivier-stasse 
@saikishor 
(I think they have to be added to the organisation as well)

[CI] Update list of reviewers

---

.github/workflows/context_testing.yml
.github/workflows/reviewer_lottery.yml

It seems that the changes of https://github.com/ros-controls/ros2_controllers/pull/946 did not work, I'll add a test commit here to debug the github context.

Don't run reviewer lottery from bots

---

.github/workflows/reviewer_lottery.yml

Maybe this works now, see https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings

[CI] Reviewer Lottery: Use contains() in if rule

---

ros2_control_demo_description/diffbot/urdf/diffbot_description.urdf.xacro
ros2_control_demo_description/rrbot/urdf/rrbot_description.urdf.xacro

While testing rqt_joint_trajectory_controller we realized that the URDFs lack limits for the continuous joints (velocity + effort).

URDF: Add limits to the continuous joints

---

ros2_control_demos/package.xml

Add example12 to meta package

---

example_2/bringup/config/diffbot_controllers.yaml
example_2/doc/userdoc.rst

See https://github.com/ros-controls/ros2_controllers/pull/812

[diff_drive] Use TwistStamped

---

example_7/reference_generator/send_trajectory.cpp

Resolves #427 by copying joint velocities into the trajectory point's velocity field. This makes no functional difference for the r6bot controller when both position and velocity are provided as shown by @christophfroehlich [here](https://github.com/ros-controls/ros2_control_demos/issues/427#issuecomment-1891645903).
Tested by echoing the `/r6bot_controller/joint_trajectory` topic. Prior to the change, both `velocities` and `positions` were always the same:
```
...
- positions:
- 0.2526216532445078
- -0.21062744421529653
- -0.3485843399000512
- -0.13795689568475478
- -1.2928197138013211e-16
- 0.25262165324450775
velocities:
- 0.2526216532445078
- -0.21062744421529653
- -0.3485843399000512
- -0.13795689568475478
- -1.2928197138013211e-16
- 0.25262165324450775
accelerations: []
effort: [] …
```

Publish correct joint velocities in r6bot example 7

---

example_14/hardware/rrbot_actuator_without_feedback.cpp
example_14/hardware/rrbot_sensor_for_position_feedback.cpp
example_2/hardware/diffbot_system.cpp
example_8/hardware/rrbot_transmissions_system_position_only.cpp

Use own implementation of `stod()`, see https://github.com/ros-controls/ros2_control/pull/1257

Use own implementation of `stod()`

---

.github/workflows/ci-ros-lint.yml
example_11/doc/userdoc.rst
example_11/hardware/include/ros2_control_demo_example_11/carlikebot_system.hpp

[CI] Use a single list for lint job

---

example_1/bringup/launch/rrbot.launch.py
example_10/bringup/launch/rrbot.launch.py
example_11/bringup/launch/carlikebot.launch.py
example_12/bringup/launch/rrbot.launch.py
example_14/bringup/launch/rrbot_modular_actuators_without_feedback_sensors_for_position_feedback.launch.py
example_14/hardware/rrbot_actuator_without_feedback.cpp
example_2/bringup/launch/diffbot.launch.py
example_3/bringup/launch/rrbot_system_multi_interface.launch.py
example_4/bringup/launch/rrbot_system_with_sensor.launch.py
example_5/bringup/launch/rrbot_system_with_external_sensor.launch.py
example_6/bringup/launch/rrbot_modular_actuators.launch.py
example_7/bringup/launch/r6bot_controller.launch.py
example_8/bringup/launch/rrbot_transmissions_system_position_only.launch.py
example_9/bringup/launch/rrbot.launch.py

This will make sure things work after https://github.com/ros-controls/ros2_control/pull/1358 is merged.
I'll update this demo by demo whenever I find the time and check the demos according to their docs after modifying them.

Update all demos using the description from topic rather than the parameter

---

.github/workflows/humble-docker-build.yaml
.github/workflows/iron-docker-build.yaml
.github/workflows/rolling-docker-build.yaml

Scheduled build always runs from the default branch, i.e., we have to specify the branch for the checkout
https://github.com/ros-controls/ros2_control_demos/actions/runs/8197668059/job/22419968638

[CI] Add ref checkout for scheduled docker builds

---

example_8/hardware/rrbot_transmissions_system_position_only.cpp

New pre-commit config introduces clang 18, which likes to reformat some parts of the code.

Satisfy clang 18

---

example_10/bringup/launch/rrbot.launch.py
example_10/description/ros2_control/rrbot.ros2_control.xacro
example_10/description/urdf/rrbot.urdf.xacro
example_10/doc/userdoc.rst

A test for reproducing https://github.com/ros-controls/ros2_control/issues/1277 but I think this is valuable also to add here.

Add GenericSystem to GPIO example

---

example_1/bringup/launch/rrbot.launch.py
example_10/bringup/launch/rrbot.launch.py
example_11/bringup/launch/carlikebot.launch.py
example_12/bringup/launch/rrbot.launch.py
example_14/bringup/launch/rrbot_modular_actuators_without_feedback_sensors_for_position_feedback.launch.py
example_14/hardware/rrbot_actuator_without_feedback.cpp
example_2/bringup/launch/diffbot.launch.py
example_3/bringup/launch/rrbot_system_multi_interface.launch.py
example_4/bringup/launch/rrbot_system_with_sensor.launch.py
example_5/bringup/launch/rrbot_system_with_external_sensor.launch.py
example_6/bringup/launch/rrbot_modular_actuators.launch.py
example_7/bringup/launch/r6bot_controller.launch.py
example_8/bringup/launch/rrbot_transmissions_system_position_only.launch.py
example_9/bringup/launch/rrbot.launch.py

This is a manual backport of #456 + necessary remapping of the robot_description topic.

Update all demos using the description from topic rather than the parameter (backport #456)

---

example_7/doc/userdoc.rst

I've removed `[]()` from the end [here](https://control.ros.org/master/doc/ros2_control_demos/example_7/doc/userdoc.html#writing-a-controller):
```cpp
using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;[]()
```
I don't think that's a valid C++ syntax (sorry, I'm a beginner in C++). Also, because [the actual code](https://github.com/ros-controls/ros2_control_demos/blob/436d3c61dfa8ccf4a810a85c702c542d1540aeba/example_7/hardware/include/ros2_control_demo_example_7/r6bot_hardware.hpp#L32) doesn't have `[]()`
(This change can be backported to Humble & Iron)

[doc] fix typo in example_7 - remove `[]()`

---

example_7/doc/userdoc.rst

[Here](https://control.ros.org/master/doc/ros2_control_demos/example_7/doc/userdoc.html#writing-a-controller), there's a typo. I changed "conforms" to "conform": 
> In ros2_control, controllers are implemented as plugins that conforms ...
(This can be backported to Humble & Iron as well)

[doc] fix typo - conform

---

doc/index.rst

That hint repeats 2 times. 
I've removed one of them:
> * Joint names in <ros2_control> tags in the URDF must be compatible with the controller's configuration.
[here](https://control.ros.org/master/doc/ros2_control_demos/doc/index.html#quick-hints)
(It can be backported to humble as well)

[doc] Remove a duplicate hint

---

example_1/doc/userdoc.rst
example_10/doc/userdoc.rst
example_11/doc/userdoc.rst
example_12/doc/userdoc.rst
example_14/doc/userdoc.rst
example_2/doc/userdoc.rst
example_3/doc/userdoc.rst
example_4/doc/userdoc.rst
example_5/doc/userdoc.rst
example_6/doc/userdoc.rst
example_8/doc/userdoc.rst
example_9/doc/userdoc.rst

Using sphinx references seems to be more robust. (linkcheck failed today while releasing the Jazzy version).

Change links to be sphinx refs

---

example_11/bringup/config/carlikebot_controllers.yaml

Is default true already, and will be removed by https://github.com/ros-controls/ros2_controllers/pull/1151

Remove stamped parameter

---

example_7/hardware/include/ros2_control_demo_example_7/r6bot_hardware.hpp

As a consequence of https://github.com/ros-controls/ros2_control/pull/1627 there is an include for HARWARE_INTERFACE_PUBLIC missing, causing the build of example_7 to fail.

Ex7: Remove visibility macro

---

ros2_control_demo_testing/ros2_control_demo_testing/test_utils.py

The code worked on noble/rolling but didn't on iron/humble at jammy. I added this already in #549 #550 but to be save I'd also push this on the rolling version.

Fix double quotes in python file

---

example_10/bringup/config/rrbot_controllers.yaml
example_10/test/test_rrbot_launch.py

The marker `@launch_testing.ready_to_test_action_timeout(20)` was not backported to humble
https://github.com/ros2/launch/pull/625
This makes now the compatibility build fail, and also stops this from backporting see #549

Remove launch testing timeout marker

---

example_1/CMakeLists.txt
example_10/CMakeLists.txt
example_11/CMakeLists.txt
example_12/CMakeLists.txt
example_14/CMakeLists.txt
example_2/CMakeLists.txt
example_3/CMakeLists.txt
example_4/CMakeLists.txt
example_5/CMakeLists.txt
example_6/CMakeLists.txt
example_7/CMakeLists.txt
example_8/CMakeLists.txt
example_9/CMakeLists.txt

We lately applied some breaking behavior changes of ros2_control to the demos (e.g., #502). The idea is now to check for the correct ros2_control version at compile-time
```
Starting >>> ros2_control_demo_example_1
--- stderr: ros2_control_demo_example_1                         
CMake Warning at CMakeLists.txt:20 (find_package):
Could not find a configuration file for package "ros2_control" that is
compatible with requested version "5.0.0".
The following configuration files were considered but not accepted:
/workspaces/ros2_rolling_ws/install/ros2_control/share/ros2_control/cmake/ros2_controlConfig.cmake, version: 4.13.0
CMake Error at CMakeLists.txt:23 (message):
ros2_control version 5.0.0 or higher is required. Are you using the correct branch of the ros2_control_demos repository?
```

Add guards for correct version of ros2_control

---

example_14/hardware/rrbot_actuator_without_feedback.cpp

See #455, which is solved upstream now.

Ex14: Remove `is_finite` check

---

example_2/doc/userdoc.rst

Updated publishing rate to match with diff_drive controller update rate (as in 3rd line of [config file](https://github.com/ros-controls/ros2_control_demos/blob/master/example_2/bringup/config/diffbot_controllers.yaml)).

Update publishing rate for example_2 in userdoc.rst

---

ros2_control_demos.jazzy.repos
ros2_control_demos.rolling.repos

https://github.com/ros-controls/gz_ros2_control/pull/408#pullrequestreview-2260392863

gz_ros2_control: Use correct branches for rolling + jazzy

---

example_1/bringup/config/rrbot_forward_position_publisher.yaml

Updated `pos2` and `pos4` values from int to float as type implicitly mentioned in parameter declaration as `rclpy.Parameter.Type.DOUBLE_ARRAY` in `publisher_forward_position_controller` and `publisher_joint_trajectory_controller`.
Fixes: #1239 in ros2_controllers

Fix deprecation warning in paramater declaration

---

example_15/CMakeLists.txt
example_15/bringup/launch/rrbot_base.launch.py
example_15/bringup/launch/rrbot_namespace.launch.py

Follow-up to #540 
Re-evalute after #502 is merged.

Reactivate tests for example_15

---

example_10/bringup/config/rrbot_forward_position_publisher.yaml
example_15/bringup/config/rrbot_namespace_forward_position_publisher.yaml
example_3/bringup/config/rrbot_forward_position_publisher.yaml
example_4/bringup/config/rrbot_forward_position_publisher.yaml
example_5/bringup/config/rrbot_forward_position_publisher.yaml
example_6/bringup/config/rrbot_forward_position_publisher.yaml
example_8/bringup/config/rrbot_forward_position_publisher.yaml
example_9/bringup/config/rrbot_forward_position_publisher.yaml

@fmauch found an issue with wrong parameter types, as we declared the type explicitly with https://github.com/ros-controls/ros2_controllers/pull/1280
```
[publisher_forward_position_controller-1] rclpy.exceptions.InvalidParameterTypeException: Trying to set parameter 'pos2' to '[0, 0]' of type 'INTEGER_ARRAY', expecting type 'DOUBLE_ARRAY': pos2
```

Fix the publisher parameter type to `DOUBLE_ARRAY`

---

example_13/CMakeLists.txt
example_13/bringup/config/three_robots_controllers.yaml
example_13/bringup/launch/three_robots.launch.py
example_13/test/test_three_robots_launch.py

Applies changes similar to #502 to #417, but this can't be backported.

[Example 13] Give the controller type as parameter in ctrl namespace

---

example_13/test/test_three_robots_launch.py

I wrote a test for a "wrong" behavior, which got fixed now in https://github.com/ros-controls/ros2_controllers/pull/1331
Closes #618

Fix test after JSB got fixed

---

example_3/doc/userdoc.rst

up to now this was only discussed with launch file parameters, not a command mode switch during runtime.

Example3: Add section on command mode switching

---

example_1/test/test_rrbot_launch.py
example_1/test/test_rrbot_launch_cli_direct.py
example_10/test/test_rrbot_launch.py
example_11/test/test_carlikebot_launch.py
example_12/test/test_rrbot_launch.py
example_13/test/test_three_robots_launch.py
example_14/test/test_rrbot_modular_actuators_without_feedback_sensors_for_position_feedback_launch.py
example_15/test/test_multi_controller_manager_launch.py
example_15/test/test_rrbot_namespace_launch.py
example_2/test/test_diffbot_launch.py
example_3/test/test_rrbot_system_multi_interface_launch.py
example_4/test/test_rrbot_system_with_sensor_launch.py
example_5/test/test_rrbot_system_with_external_sensor_launch.py
example_6/test/test_rrbot_modular_actuators_launch.py
example_7/test/test_r6bot_controller_launch.py
example_8/test/test_rrbot_transmissions_system_position_only_launch.py
example_9/test/test_rrbot_launch.py

I followed the guidelines of https://docs.ros.org/en/rolling/p/launch_testing/index.html
I was not aware that `setUp`/`tearDown` will be called for every test case.

Use class methods for rclpy.init/shutdown

---

example_13/CMakeLists.txt
example_13/bringup/launch/three_robots.launch.py
example_13/package.xml
example_13/test/test_three_robots_launch.py

Adressing #640, maybe this fixes the flakyness.

Use launch_utils instead of a spawner per controller

---

example_7/controller/include/ros2_control_demo_example_7/r6bot_controller.hpp
example_7/doc/userdoc.rst

Fix compilation after https://github.com/ros-controls/ros2_control/pull/1972

Remove the use of visibility macros

---

example_11/test/test_carlikebot_launch.py

According to the API description of `WaitForTopics` https://docs.ros.org/en/rolling/p/launch_testing_ros/launch_testing_ros.wait_for_topics.html
In the other occurrences we had that already.

Add missing shutdown call in test class

---

doc/index.rst

Fixes #704 
Changed `rviz2 -d src/ros2_control_demos/example_1/description/rviz/rrbot.rviz` to 
`rviz2 -d src/ros2_control_demos/ros2_control_demo_description/rrbot/rviz/rrbot.rviz` where found.

Fixed command path to rviz file.

---

example_11/CMakeLists.txt
example_11/bringup/launch/carlikebot.launch.py
example_11/test/test_carlikebot_launch_remapped.py

The remap_odometry_tf launch file argument was not cleaned up properly with #577

Fix remapping arg in launch file and tests

---

example_1/test/test_rrbot_launch_cli_direct.py
example_11/test/test_carlikebot_launch_remapped.py
example_14/test/test_rrbot_modular_actuators_without_feedback_sensors_for_position_feedback_launch.py

Those were forgotten with #548 
example_14 still fails, see #721

Activate assertExitCodes for missing tests

---

example_1/package.xml
example_10/package.xml
example_11/package.xml
example_12/package.xml
example_13/package.xml
example_14/package.xml
example_15/package.xml
example_2/package.xml
example_3/package.xml
example_4/package.xml
example_5/package.xml
example_6/package.xml
example_7/package.xml
example_8/package.xml
example_9/package.xml

I realized that there is a mess with the test dependencies
- I added missing `test_depend` like launch_testing, and removed unused ones.
- I removed duplicates, which were already defined in as `exec_depend`, see [the docs](https://docs.ros.org/en/rolling/Tutorials/Intermediate/Rosdep.html#test-depend).
- I reorderd some xmls to satisfy the linter

Cleanup dependencies and update metadata in package.xml

---

example_1/hardware/rrbot.cpp

Was a simple test to see if rw_rate is set during on_init() call.

Print hardware component's rw_rate in example_1

---

example_16/README.md
example_16/doc/userdoc.rst

Fix https://github.com/ros-controls/ros2_control_demos/issues/742 and a text indentation issue for Tutorial [steps 2](https://control.ros.org/rolling/doc/ros2_control_demos/example_16/doc/userdoc.html#tutorial-steps). 
- Changes have been tested locally by following instructions from https://github.com/ros-controls/control.ros.org?tab=readme-ov-file#build-instructions.

Fix broken links and text indentation in example_16 doc

---

example_9/bringup/config/rrbot_controllers.yaml
example_9/bringup/launch/rrbot_gazebo.launch.py
example_9/description/gazebo/rrbot.gazebo.xacro
example_9/package.xml

The main change is to add a Gazebo [bridge node](https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_bridge/README.md) to fix following Gazebo runtime error after launching the example. The error will cause Gazebo to be terminated. 
```
ros2 launch ros2_control_demo_example_9 rrbot_gazebo.launch.py gui:=true
[gazebo-1] terminate called after throwing an instance of 'std::runtime_error'
[gazebo-1]   what():  can't compare times with different time sources
[gazebo-1] Stack trace (most recent call last) in thread 270397:
[gazebo-1] #14   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
[gazebo-1] #13   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7d5de3d29c3b, in 
[gazebo-1] #12   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7d5de3c9caa3, in 
[gazebo-1] #11   Object …
```

[example_9] Add gazebo bridge node for clock sync-ing

---

example_13/test/test_three_robots_launch.py
example_15/test/test_multi_controller_manager_launch.py
example_15/test/test_rrbot_namespace_launch.py

fixes https://github.com/ros-controls/ros2_control_ci/issues/287
the test finished sending SIGINTs to all processes, but the spawner for the inactive controller was not finished yet. If we check also for the inactive controller to be spawend, this should not happen anymore.

Test also for the inactive controller

---

example_5/hardware/external_rrbot_force_torque_sensor.cpp

This is needed after we merged the latest changes for boolean suuport. Floats are not casted anymore, it will only caused compilation error
https://github.com/ros-controls/ros2_control/actions/runs/14365884755/job/40278566870

[Example 5] Cast to double in the force torque HW interface

---

example_14/hardware/rrbot_sensor_for_position_feedback.cpp

I introduced a bug with #653: The state interfaces are joints, and not sensors -> the joints haven't been set to zero -> the integration step starts from NaN and stays there.

Use joint_state_interfaces in RRBotSensorPositionFeedback

---

example_7/controller/r6bot_controller.cpp

Fix applied from #793 . Note that behaviour is very similar, to the point of not being noticed, due to the controller frequency reducing visible errors. This merely corrects the example to have the right maths.

Correct interpolation of example_7 to use both points (#793)

---

example_7/bringup/launch/r6bot_controller.launch.py
example_7/controller/r6bot_controller.cpp
example_7/reference_generator/send_trajectory.cpp

Thanks to debugging by @catarina-p and myself, we found issues with the 6DOF arm example.
Turns out the controller kept extrapolating forever past the final point, meaning that instead of slowing down from positive to zero velocity, the velocities kept going negative further and further.
Before this fix:
https://github.com/user-attachments/assets/af815279-818a-4922-837d-94b0208035cc
After this fix:
https://github.com/user-attachments/assets/70f4796e-38e1-4ba5-b2f2-5e402c324f2c
I also did some cleanup of the trajectory time calculations since the final point's time was not exactly 3.0 as expected.
Edit: As a side note, I am somewhat surprised that this example doesn't just use the regular joint trajectory controller that is already available in ros2_control. Although it's a nice example …

Fix 6DOF arm example

---

ros2_control_demo_description/CMakeLists.txt
ros2_control_demos/CMakeLists.txt

CMake < 3.10 is deprecated on some platforms https://github.com/ros-controls/ros2_control_cmake/pull/8#pullrequestreview-2904365381

Update cmake_minimum_required VERSION

---

example_3/hardware/rrbot_system_multi_interface.cpp

I have the feeling that the log output at 100Hz clogs the RMW resulting in test errors like here
https://github.com/ros-controls/ros2_control_ci/issues/476

Throttle the log output
